const fs = require('node:fs');
const {renderPage} = require('./products.cjs');
fs.writeFileSync('index.html', renderPage(JSON.parse(fs.readFileSync('data/products.json', 'utf8'))));
require('./check.cjs');
require('./test-products.cjs');
fs.rmSync('dist', {recursive:true, force:true});
fs.mkdirSync('dist/assets', {recursive:true});
fs.cpSync('characters', 'dist/characters', {recursive:true});
fs.cpSync('assets/identity', 'dist/assets/identity', {recursive:true});
fs.cpSync('assets/products', 'dist/assets/products', {recursive:true});
for (const file of ['index.html','resume.html','robots.txt','sitemap.xml','.nojekyll']) fs.copyFileSync(file, `dist/${file}`);
for (const file of ['constellation.css','constellation.js','home.css','home-motion.js','catalog.js','styles.css','resume.css','site.js','identity.css','favicon.svg','unilifesim.jpg','certificate.jpg']) fs.copyFileSync(`assets/${file}`, `dist/assets/${file}`);
console.log('Built public-only static files in dist');
