(() => {
'use strict';
const $=id=>document.getElementById(id), key='literary-map-v1', colors={'亲属':'#608b79','婚姻':'#bb774e','交往':'#6f82a9'};
const sample={title:'红楼梦 · 第三回选读',nodes:[['jm','贾母','贾府长辈，林黛玉的外祖母。'],['ldy','林黛玉','林如海与贾敏之女，本回进入荣国府。'],['l rh','林如海','林黛玉之父，托贾政帮助贾雨村复职。'],['jmin','贾敏','林黛玉之母，贾母之女；本回叙事时已去世。'],['jz','贾政','贾母之子，林黛玉的二舅。'],['js','贾赦','贾母之子，林黛玉的大舅。'],['jby','贾宝玉','王夫人之子，本回与林黛玉初见。'],['wfr','王夫人','贾政之妻，贾宝玉之母。']].map(([id,name,note])=>({id,name,note})),edges:[['jm','ldy','亲属','贾母是黛玉的外祖母'],['l rh','ldy','亲属','林如海是黛玉的父亲'],['jmin','ldy','亲属','贾敏是黛玉的母亲'],['jm','jmin','亲属','贾母是贾敏的母亲'],['jm','jz','亲属','贾母是贾政的母亲'],['jm','js','亲属','贾母是贾赦的母亲'],['jz','wfr','婚姻','贾政与王夫人为夫妻'],['wfr','jby','亲属','王夫人是宝玉的母亲'],['jby','ldy','交往','本回在贾府初次相见'],['l rh','jmin','婚姻','林如海与贾敏为夫妻']].map(([from,to,type,label])=>({from,to,type,label}))};
let data=structuredClone(sample),custom=null,selected=null,zoom=1,drag=null,moved=false;
const tell=s=>$('status').textContent=s;
function validate(d){if(!d||typeof d.title!=='string'||d.title.length>80||!Array.isArray(d.nodes)||!Array.isArray(d.edges)||d.nodes.length>60||d.edges.length>200)throw Error('图谱格式不正确；最多 60 人、200 条关系。');const ids=new Set();for(const n of d.nodes){if(typeof n.id!=='string'||!n.id||n.id.length>80||ids.has(n.id)||typeof n.name!=='string'||!n.name.trim()||n.name.length>20||typeof n.note!=='string'||n.note.length>600)throw Error('人物字段不正确或 ID 重复。');ids.add(n.id);if(n.x!==undefined&&(!Number.isFinite(n.x)||n.x<40||n.x>760))delete n.x;if(n.y!==undefined&&(!Number.isFinite(n.y)||n.y<40||n.y>580))delete n.y;}for(const e of d.edges)if(!ids.has(e.from)||!ids.has(e.to)||e.from===e.to||!Object.hasOwn(colors,e.type)||typeof e.label!=='string'||!e.label.trim()||e.label.length>80)throw Error('关系字段或人物引用不正确。');return d;}
try{const raw=localStorage.getItem(key);if(raw)custom=validate(JSON.parse(raw));}catch{tell('保存的数据无法读取；可以重新导入备份。');}
function save(){custom=structuredClone(data);$('book').value='custom';document.body.dataset.custom='true';try{localStorage.setItem(key,JSON.stringify(custom));tell('已保存在此浏览器。建议导出一份备份。');}catch{tell('浏览器无法保存，请立即导出图谱备份。');}}
function node(id){return data.nodes.find(n=>n.id===id);}
function element(tag,attrs={},text){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;}
function focus(id){selected=id;$('name').value=node(id)?.name||'';$('note').value=node(id)?.note||'';render();}
function render(){const term=$('search').value.trim(),type=$('filter').value;const visible=data.nodes.filter(n=>n.name.includes(term));const ids=new Set(visible.map(n=>n.id));const edges=data.edges.filter(e=>ids.has(e.from)&&ids.has(e.to)&&(type==='all'||e.type===type));$('bookTitle').textContent=data.title;$('count').textContent=`${visible.length} 位人物 · ${edges.length} 条关系`;$('empty').hidden=visible.length>0;$('people').replaceChildren();for(const n of visible){const b=document.createElement('button');b.textContent=n.name;b.classList.toggle('selected',n.id===selected);b.setAttribute('aria-pressed',String(n.id===selected));b.onclick=()=>focus(n.id);$('people').append(b);}
const svg=$('graph');svg.replaceChildren();svg.setAttribute('viewBox',`${400-400/zoom} ${310-310/zoom} ${800/zoom} ${620/zoom}`);data.nodes.forEach((n,i)=>{if(!Number.isFinite(n.x)){const a=i/data.nodes.length*Math.PI*2-Math.PI/2;n.x=400+260*Math.cos(a);n.y=310+230*Math.sin(a);}});const neighbors=new Set([selected]);edges.forEach(e=>{if(e.from===selected)neighbors.add(e.to);if(e.to===selected)neighbors.add(e.from);});
for(const e of edges){const a=node(e.from),b=node(e.to),on=!selected||e.from===selected||e.to===selected;svg.append(element('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:colors[e.type],'stroke-width':on?2.5:1,opacity:on?.75:.15,'stroke-dasharray':e.type==='交往'?'6 5':''}));if(selected&&on)svg.append(element('text',{x:(a.x+b.x)/2,y:(a.y+b.y)/2-7,'text-anchor':'middle','font-size':13,fill:colors[e.type],stroke:'#f0f3eb','stroke-width':4,'paint-order':'stroke'},e.label));}
for(const n of visible){const g=element('g',{'data-id':n.id,class:'node',transform:`translate(${n.x} ${n.y})`,opacity:!selected||neighbors.has(n.id)?1:.35});g.append(element('circle',{r:n.id===selected?35:30,fill:n.id===selected?'#24483e':'#fffdf8',stroke:n.id===selected?'#24483e':'#a1b6a5','stroke-width':2}),element('text',{'text-anchor':'middle',dy:5,'font-size':14,fill:n.id===selected?'#fff':'#24483e'},n.name));svg.append(g);}
const n=node(selected);$('personTitle').textContent=n?.name||'选择一个人物';$('bio').textContent=n?.note||'从左侧列表或图中选择人物，查看关系与阅读笔记。';$('relations').replaceChildren();const relevant=edges.filter(e=>e.from===selected||e.to===selected);if(n&&!relevant.length){$('relations').textContent='当前筛选条件下没有相关关系。';}for(const e of relevant){const div=document.createElement('div');div.className='relation';const p=document.createElement('p');p.textContent=e.label;const small=document.createElement('small');small.textContent=`${node(e.from).name} — ${node(e.to).name} · ${e.type}`;const del=document.createElement('button');del.textContent='移除';del.onclick=()=>{data.edges.splice(data.edges.indexOf(e),1);save();render();};div.append(del,p,small);$('relations').append(div);}for(const id of ['from','to']){const value=$(id).value;$(id).replaceChildren();for(const n of data.nodes){const o=document.createElement('option');o.value=n.id;o.textContent=n.name;$(id).append(o);}if(node(value))$(id).value=value;}$('delete').disabled=!n;
}
$('search').oninput=render;$('filter').onchange=render;$('clear').onclick=()=>focus(null);
$('book').onchange=()=>{data=structuredClone($('book').value==='sample'?sample:custom||{title:'我的阅读图谱',nodes:[],edges:[]});document.body.dataset.custom=String($('book').value==='custom');selected=null;$('search').value='';$('filter').value='all';focus(null);};
$('new').onclick=()=>{if(custom&&!confirm('新建会替换此浏览器中的自定义图谱。请先导出备份，是否继续？'))return;data={title:'我的阅读图谱',nodes:[],edges:[]};selected=null;$('search').value='';save();focus(null);$('name').focus();};
$('personForm').onsubmit=e=>{e.preventDefault();const name=$('name').value.trim(),note=$('note').value.trim();if(!name)return;if(data.nodes.some(n=>n.name===name&&n.id!==selected))return tell('已存在同名人物。');let n=node(selected);if(n)Object.assign(n,{name,note});else{if(data.nodes.length>=60)return tell('最多可添加 60 位人物。');n={id:crypto.randomUUID(),name,note};data.nodes.push(n);}save();focus(n.id);};
$('delete').onclick=()=>{if(!selected||!confirm('删除该人物及其所有关系？'))return;data.nodes=data.nodes.filter(n=>n.id!==selected);data.edges=data.edges.filter(e=>e.from!==selected&&e.to!==selected);selected=null;save();focus(null);};
$('edgeForm').onsubmit=e=>{e.preventDefault();const from=$('from').value,to=$('to').value,type=$('type').value,label=$('label').value.trim();if(!from||!to||from===to)return tell('请选择两个不同的人物。');if(!label)return;if(data.edges.length>=200)return tell('最多可添加 200 条关系。');if(data.edges.some(e=>e.from===from&&e.to===to&&e.label===label))return tell('该关系已存在。');data.edges.push({from,to,type,label});save();focus(from);};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='literary-characters.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);tell('图谱已导出，可在其他浏览器导入。');};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>300000)throw Error('文件不能超过 300 KB。');const next=validate(JSON.parse(await f.text()));if(custom&&!confirm('导入会替换已保存的自定义图谱，是否继续？'))return;data=next;selected=null;$('search').value='';$('filter').value='all';save();focus(null);}catch(err){tell('导入失败：'+err.message);}finally{e.target.value='';}};
$('in').onclick=()=>{zoom=Math.min(2,zoom+.2);render();};$('out').onclick=()=>{zoom=Math.max(.6,zoom-.2);render();};$('reset').onclick=()=>{zoom=1;data.nodes.forEach(n=>{delete n.x;delete n.y;});render();};
const graph=$('graph');graph.onpointerdown=e=>{const g=e.target.closest('[data-id]');if(!g)return;drag=g.dataset.id;moved=false;graph.setPointerCapture(e.pointerId);};graph.onpointermove=e=>{if(!drag)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(graph.getScreenCTM().inverse());const n=node(drag);if(Math.hypot(n.x-p.x,n.y-p.y)>3)moved=true;n.x=Math.max(40,Math.min(760,p.x));n.y=Math.max(40,Math.min(580,p.y));render();};graph.onpointerup=()=>{if(!drag)return;const id=drag;drag=null;if(moved&&$('book').value==='custom')save();focus(id);};graph.onpointercancel=()=>{drag=null;};render();
})();
